export const languages = {
	English: {
		autoInsurance: "Auto Insurance",
		homeInsurance: "Home Insurance",
		agentName: "Agent Name",
		csrName: "CSR",
		clientName: "Client Name",
		carrier: "Insurance Carrier",
		policyTerm: "Policy Term",
		months: "Months",
		quoteNumber: "Quote Number",
		coverageOptions: "Coverage Options",
		fullCoverage: "Full Coverage",
		liabilityOnly: "Liability Only",
		deductible: "Deductible",
		bodilyInjury: "Bodily Injury",
		medicalPayments: "Medical Payments",
		propertyDamage: "Property Damage",
		rentalCar: "Rental Car Coverage",
		gapInsurance: "Gap Insurance",
		extraCoverage: "Extra Coverage",
		rentersInsurance: "Renters Insurance",
		rentersFirstPayment: "Renters First Payment ($)",
		rentersMonthlyPayment: "Renters Monthly Payment ($)",
		rentersMessage:
			"Renters was included to guarantee price possible and give you extra coverage.",
		addFee: "Add Fee",
		feeAmount: "Fee Amount ($)",
		feeMessage:
			"This fee will be added to the first payment and annual premium only.",
		paymentAmounts: "Payment Amounts",
		firstPayment: "First Payment ($)",
		monthlyPayment: "Monthly Payment ($)",
		fullPayment: "Full Payment ($)",
		generateQuote: "Generate Quote",
		generatingQuote: "Generating Quote...",
		generateNewQuote: "Generate New Quote",
		downloadQuote: "Download Quote Image",
		warningMessage:
			"Valid only for drivers listed on the policy; does not cover accidents for unlisted drivers.",
		selectAgent: "Select agent",
		selectCSR: "Select CSR",
		selectCarrier: "Select carrier",
		customCarrier: "Custom Carrier",
		customAgent: "Custom Agent",
		enterQuoteNumber: "Enter quote number (optional)",
		selectAmount: "Select amount",
		none: "None",
		language: "Language",
		newQuote: "New Quote",
		savedQuotes: "Saved Quotes",
		editingQuote: "Editing Quote",
		requiredField: "This field is required",
		vehicles: "Vehicles",
		vehicle: "Vehicle",
		addVehicle: "Add Vehicle",
		removeVehicle: "Remove Vehicle",
		vehicleName: "Vehicle Description",
		enterVehicleName: "Enter year, make and model",
		vehicleTab: "Vehicle",
		autoInsuranceType: "Auto",
		commercialAutoInsuranceType: "Commercial Auto",
		insuranceTypeLabel: "Insurance Type",
		alternativeOptions: "Alternative Coverage Options",
		addAlternativeOption: "Add Alternative Option",
		alternativeOptionName: "Option Name",
		typeToAddAvehicle: "Type to add a vehicle",
		removeAlternativeOption: "Remove Option",
		mainCoverage: "Main Coverage",
		alternativeOption: "Alternative Option",
		alternativeOptionNamePlaceholder: "Enter option name (e.g. Liability Only)",
		backToMainCoverage: "Back to Main Coverage",
		alternativeOptionsExplanation:
			"Add alternative coverage options to show different pricing options for this vehicle",
		mainTitle: "Insurance Quote Generator",
		generateQuoteBtn: "Generate Quote",
		savedQuotesTitle: "Saved Quotes",
	},
	Português: {
		autoInsurance: "Seguro de Automóvel",
		homeInsurance: "Seguro Residencial",
		agentName: "Nome do Agente",
		csrName: "CSR",
		clientName: "Nome do Cliente",
		carrier: "Seguradora",
		policyTerm: "Prazo da Apólice",
		months: "Meses",
		quoteNumber: "Número da Cotação",
		coverageOptions: "Opções de Cobertura",
		fullCoverage: "Cobertura Total",
		liabilityOnly: "Somente cobertura para terceiros",
		deductible: "Franquia",
		bodilyInjury: "Danos Corporais",
		medicalPayments: "Pagamentos Médicos",
		propertyDamage: "Danos Materiais",
		rentalCar: "Cobertura de Carro de Aluguel",
		gapInsurance: "Seguro GAP",
		extraCoverage: "Cobertura Extra",
		rentersInsurance: "Seguro de Inquilino",
		rentersFirstPayment: "Primeiro Pagamento do Seguro de Inquilino ($)",
		rentersMonthlyPayment: "Pagamento Mensal do Seguro de Inquilino ($)",
		rentersMessage:
			"Seguro de inquilino foi incluído para garantir o melhor preço possível e dar cobertura extra.",
		addFee: "Adicionar Taxa",
		feeAmount: "Valor da Taxa ($)",
		feeMessage:
			"Esta taxa será adicionada apenas ao primeiro pagamento e ao prêmio anual.",
		paymentAmounts: "Valores de Pagamento",
		firstPayment: "Primeiro Pagamento ($)",
		monthlyPayment: "Pagamento Mensal ($)",
		fullPayment: "Pagamento Total ($)",
		generateQuote: "Gerar Cotação",
		generatingQuote: "Gerando Cotação...",
		generateNewQuote: "Gerar Nova Cotação",
		downloadQuote: "Baixar Imagem da Cotação",
		warningMessage:
			"Válido apenas para motoristas listados na apólice; não cobre acidentes para motoristas não listados.",
		selectAgent: "Selecione o agente",
		selectCSR: "Selecione o CSR",
		selectCarrier: "Selecione a seguradora",
		customCarrier: "Seguradora Personalizada",
		customAgent: "Agente Personalizado",
		enterQuoteNumber: "Digite o número da cotação (opcional)",
		selectAmount: "Selecione o valor",
		none: "Nenhum",
		language: "Idioma",
		newQuote: "Nova Cotação",
		savedQuotes: "Cotações Salvas",
		editingQuote: "Editando Cotação",
		requiredField: "Este campo é obrigatório",
		vehicles: "Veículos",
		vehicle: "Veículo",
		addVehicle: "Adicionar Veículo",
		removeVehicle: "Remover Veículo",
		vehicleName: "Descrição do Veículo",
		enterVehicleName: "Digite ano, marca e modelo",
		typeToAddAvehicle: "Digite para adicionar um veículo",
		vehicleTab: "Veículo",
		autoInsuranceType: "Auto",
		commercialAutoInsuranceType: "Auto Comercial",
		insuranceTypeLabel: "Tipo de Seguro",
		alternativeOptions: "Opções Alternativas de Cobertura",
		addAlternativeOption: "Adicionar Opção Alternativa",
		alternativeOptionName: "Nome da Opção",
		removeAlternativeOption: "Remover Opção",
		mainCoverage: "Cobertura Principal",
		alternativeOption: "Opção Alternativa",
		alternativeOptionNamePlaceholder:
			"Digite o nome da opção (ex: Somente para Terceiros)",
		backToMainCoverage: "Voltar para Cobertura Principal",
		alternativeOptionsExplanation:
			"Adicione opções alternativas de cobertura para mostrar diferentes preços para este veículo",
		mainTitle: "Gerador de cotação de seguro",
		generateQuoteBtn: "Gerar cotação",
		savedQuotesTitle: "Cotações Salvas",
	},
	Español: {
		autoInsurance: "Seguro de Auto",
		homeInsurance: "Seguro de Hogar",
		agentName: "Nombre del Agente",
		csrName: "CSR",
		clientName: "Nombre del Cliente",
		carrier: "Aseguradora",
		policyTerm: "Plazo de la Póliza",
		months: "Meses",
		quoteNumber: "Número de Cotización",
		coverageOptions: "Opciones de Cobertura",
		fullCoverage: "Cobertura Completa",
		liabilityOnly: "Solo Responsabilidad Civil",
		deductible: "Deducible",
		bodilyInjury: "Lesiones Corporales",
		medicalPayments: "Pagos Médicos",
		propertyDamage: "Daños a la Propiedad",
		rentalCar: "Cobertura de Auto de Alquiler",
		gapInsurance: "Seguro GAP",
		extraCoverage: "Cobertura adicional",
		rentersInsurance: "Seguro de Inquilino",
		rentersFirstPayment: "Primer Pago del Seguro de Inquilino ($)",
		rentersMonthlyPayment: "Pago Mensual del Seguro de Inquilino ($)",
		rentersMessage:
			"Se incluyó seguro de inquilino para garantizar el mejor precio posible y darle cobertura adicional.",
		addFee: "Agregar Tarifa",
		feeAmount: "Monto de la Tarifa ($)",
		feeMessage:
			"Esta tarifa se agregará solo al primer pago y a la prima anual.",
		paymentAmounts: "Montos de Pago",
		firstPayment: "Primer Pago ($)",
		monthlyPayment: "Pago Mensual ($)",
		fullPayment: "Pago Completo ($)",
		generateQuote: "Generar Cotización",
		generatingQuote: "Generando Cotización...",
		generateNewQuote: "Generar Nueva Cotización",
		downloadQuote: "Descargar Imagen de Cotización",
		warningMessage:
			"Válido solo para conductores listados en la póliza; no cubre accidentes para conductores no listados.",
		selectAgent: "Seleccione agente",
		selectCSR: "Seleccione CSR",
		selectCarrier: "Seleccione aseguradora",
		customCarrier: "Aseguradora Personalizada",
		customAgent: "Agente Personalizado",
		enterQuoteNumber: "Ingrese número de cotización (opcional)",
		selectAmount: "Seleccione monto",
		none: "Ninguno",
		language: "Idioma",
		newQuote: "Nueva Cotización",
		savedQuotes: "Cotizaciones Guardadas",
		editingQuote: "Editando Cotización",
		requiredField: "Este campo es obligatorio",
		vehicles: "Vehículos",
		vehicle: "Vehículo",
		addVehicle: "Agregar Vehículo",
		removeVehicle: "Eliminar Vehículo",
		vehicleName: "Descripción del Vehículo",
		enterVehicleName: "Ingrese año, marca y modelo",
		vehicleTab: "Vehículo",
		autoInsuranceType: "Auto",
		commercialAutoInsuranceType: "Auto Comercial",
		insuranceTypeLabel: "Tipo de Seguro",
		alternativeOptions: "Opciones Alternativas de Cobertura",
		addAlternativeOption: "Agregar Opción Alternativa",
		typeToAddAvehicle: "Escriba para agregar un vehículo",
		alternativeOptionName: "Nombre de la Opción",
		removeAlternativeOption: "Eliminar Opción",
		mainCoverage: "Cobertura Principal",
		alternativeOption: "Opción Alternativa",
		alternativeOptionNamePlaceholder:
			"Ingrese nombre de la opción (ej: Solo Responsabilidad Civil)",
		backToMainCoverage: "Volver a Cobertura Principal",
		alternativeOptionsExplanation:
			"Agregue opciones alternativas de cobertura para mostrar diferentes precios para este vehículo",
		mainTitle: "Generador de Cotización de Seguro",
		generateQuoteBtn: "Generar Cotización",
		savedQuotesTitle: "Cotizaciones Guardadas",
	},
	Kreyòl_Ayisyen: {
		autoInsurance: "Asirans Machin",
		homeInsurance: "Asirans Kay",
		agentName: "Non Ajan",
		csrName: "CSR",
		clientName: "Non Kliyan",
		carrier: "Konpayi Asirans",
		policyTerm: "Dire Kontra",
		months: "Mwa",
		quoteNumber: "Nimewo Estimasyon",
		coverageOptions: "Opsyon Pwoteksyon",
		fullCoverage: "Pwoteksyon Konplè",
		liabilityOnly: "kouvéti machine enplike",
		deductible: "Dediktib",
		bodilyInjury: "Blesi Kòporèl",
		medicalPayments: "Peman Medikal",
		propertyDamage: "Domaj Pwopriyete",
		rentalCar: "Pwoteksyon Machin Lwaye",
		gapInsurance: "Asirans GAP",
		extraCoverage: "Kouvèti siplemantè",
		rentersInsurance: "Asirans Lokatè",
		rentersFirstPayment: "Premye Peman Asirans Lokatè ($)",
		rentersMonthlyPayment: "Peman Mansyèl Asirans Lokatè ($)",
		rentersMessage:
			"Asirans lokatè te enkli pou garanti pi bon pri posib epi ba ou pwoteksyon siplemantè.",
		addFee: "Ajoute Frè",
		feeAmount: "Montan Frè ($)",
		feeMessage:
			"Frè sa a pral ajoute sèlman nan premye peman ak prim anyèl la.",
		paymentAmounts: "Montan Peman",
		firstPayment: "Premye Peman ($)",
		monthlyPayment: "Peman Mansyèl ($)",
		fullPayment: "Peman Konplè ($)",
		generateQuote: "Jenere Estimasyon",
		generatingQuote: "Ap Jenere Estimasyon...",
		generateNewQuote: "Jenere Nouvo Estimasyon",
		downloadQuote: "Telechaje Imaj Estimasyon",
		warningMessage:
			"Valab sèlman pou chofè ki nan lis sou kontra a; pa kouvri aksidan pou chofè ki pa nan lis.",
		selectAgent: "Chwazi ajan",
		selectCSR: "Chwazi CSR",
		selectCarrier: "Chwazi konpayi asirans",
		customCarrier: "Konpayi Asirans Pèsonalize",
		customAgent: "Ajan Pèsonalize",
		enterQuoteNumber: "Antre nimewo estimasyon (opsyonèl)",
		selectAmount: "Chwazi montan",
		none: "Okenn",
		language: "Lang",
		newQuote: "Nouvo Estimasyon",
		savedQuotes: "Estimasyon Sove",
		editingQuote: "Modifye Estimasyon",
		requiredField: "Chan sa a obligatwa",
		vehicles: "Machin yo",
		vehicle: "Machin",
		addVehicle: "Ajoute Machin",
		removeVehicle: "Retire Machin",
		vehicleName: "Deskripsyon Machin",
		enterVehicleName: "Antre ane, mak ak modèl",
		vehicleTab: "Machin",
		autoInsuranceType: "Machin",
		commercialAutoInsuranceType: "Machin Komèsyal",
		insuranceTypeLabel: "Tip Asirans",
		alternativeOptions: "Opsyon Pwoteksyon Altènatif",
		typeToAddAvehicle: "Tape pou ajoute yon machin",
		addAlternativeOption: "Ajoute Opsyon Altènatif",
		alternativeOptionName: "Non Opsyon",
		removeAlternativeOption: "Retire Opsyon",
		mainCoverage: "Pwoteksyon Prensipal",
		alternativeOption: "Opsyon Altènatif",
		alternativeOptionNamePlaceholder:
			"Antre non opsyon an (egzanp: Kouvèti Responsabilite Sèlman)",
		backToMainCoverage: "Retounen nan Pwoteksyon Prensipal",
		alternativeOptionsExplanation:
			"Ajoute opsyon pwoteksyon altènatif pou montre diferan pri pou machin sa a",
		mainTitle: "Jenere Estimasyon Asirans",
		generateQuoteBtn: "Jenere Estimasyon",
		savedQuotesTitle: "Estimasyon Sove",
	},
};

export const agentNames = [
	"Joao da Silva",
	"Gustavo Fraga",
	"Jhonathan Oliveira",
	"Maria Vieira",
];
